force-app/main/default/objects/BankCard__c/BankCard__c.object-meta.xml
<CustomObject>
    <label>Bank Card</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>BankCard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BankCard__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <defaultValue>2500.00</defaultValue>
    <label>Balance</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BankCard__c/fields/BankEmitter__c.field-meta.xml
<CustomField>
    <fullName>BankEmitter__c</fullName>
    <defaultValue>&#39;U.S. Bank&#39;</defaultValue>
    <label>Bank Emitter</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankCard__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>25</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/BankCard__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <label>Owner</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Bank Cards</relationshipLabel>
    <relationshipName>BankCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/DefaultCardId__c.field-meta.xml
<CustomField>
    <fullName>DefaultCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Card</label>
    <referenceTo>BankCard__c</referenceTo>
    <relationshipLabel>Bank Cards</relationshipLabel>
    <relationshipName>DefaultCard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OnlineStoreBankingController.cls
public with sharing class OnlineStoreBankingController {
    @AuraEnabled
    public static String setDefaultCard(String userId, String cardId) {
        User__c user = [SELECT Id, DefaultCardId__c FROM User__c WHERE Id = :userId LIMIT 1];
        BankCard__c card = [SELECT Id, OwnerId__c FROM BankCard__c WHERE Id = :cardId LIMIT 1];

        if (user.Id != card.OwnerId__c) return '';

        user.DefaultCardId__c = cardId;
        update user;

        return cardId;
    }
    
    /*
    TODO: Delete
    private static BankCard__c getCard(String cardId) {
        return [
            SELECT Id, Number__c, BankEmitter__c, Balance__c, OwnerId__c 
            FROM BankCard__c 
            WHERE Id = :cardId 
            LIMIT 1
        ];
    }
    */

    @AuraEnabled
    public static List<BankCard__c> getCards(String userId) {
        return [
            SELECT Id, Number__c, BankEmitter__c, Balance__c, OwnerId__c 
            FROM BankCard__c 
            WHERE OwnerId__c = :userId
        ];
    }

    @AuraEnabled
    public static BankCard__c saveNewCard(BankCard__c newCard) {
        // Emulation only 
        newCard.Balance__c = genRandomDoubleInRange(2000, 3000); // USD
        return saveCard(newCard);
    }

    private static Double genRandomDoubleInRange(Integer min, Integer max) {
        return (Double)(min + Math.random() * (max - min));
    }

    private static BankCard__c saveCard(BankCard__c card) {
        upsert card;
        return card;
    }

    @AuraEnabled
    public static Boolean deleteCard(String cardId) {
        BankCard__c card = [SELECT Id FROM BankCard__c WHERE Id = :cardId];
        delete card;
        return true;
    }
}