force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;Added&#39;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Added</fullName>
                <default>true</default>
                <label>Added</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cart__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Cart</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <defaultValue>&#39;/images/no-image.jpg&#39;</defaultValue>
    <label>Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/InStock__c.field-meta.xml
<CustomField>
    <fullName>InStock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>In Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OnlineStoreCartController.cls
public with sharing class OnlineStoreCartController {
    public inherited sharing class InvalidInputException extends Exception {}
    
    public static String added = 'Added';
    public static String paid = 'Paid';
    public static String noSuchQuantity = 'There is no such quantity in stock.';

    @AuraEnabled
    public static Integer addToCart(String userId, String productId, Integer quantity) {
        User__c user = [
            SELECT Id, (
                SELECT Quantity__c 
                FROM Carts__r
                WHERE ProductId__c = :productId
                    AND Status__c = :added
            ) 
            FROM User__c 
            WHERE Id = :userId 
            LIMIT 1
        ];
        Product__c product = [SELECT InStock__c FROM Product__c WHERE Id = :productId LIMIT 1];
        List<Cart__c> existingRecords = user.Carts__r;

        Integer cartItemsCount = [SELECT COUNT() FROM Cart__c WHERE UserId__c = :userId AND Status__c = :added];

        if (existingRecords.size() > 0) {
            Cart__c record = existingRecords[0];
            record.Quantity__c += quantity;

            if (record.Quantity__c > product.InStock__c) {
                throw new InvalidInputException(noSuchQuantity);
            }

            update record;
            return cartItemsCount;
        } else {
            if (quantity > product.InStock__c) {
                throw new InvalidInputException(noSuchQuantity);
            }

            insert new Cart__c(
                UserId__c = userId,
                ProductId__c = productId,
                Quantity__c = quantity,
                Status__c = added
            );
            return cartItemsCount + 1;
        }
    }

    @AuraEnabled
    public static Boolean updateQuantity(String userId, String productId, Integer quantity) {
        if (quantity == 0) return removeFromCart(userId, productId);

        Cart__c existingRecord = [
            SELECT Id, Quantity__c, ProductId__r.InStock__c 
            FROM Cart__c 
            WHERE UserId__c = :userId AND ProductId__c = :productId AND Status__c = :added
            LIMIT 1
        ];

        if (quantity > existingRecord.ProductId__r.InStock__c) {
            throw new InvalidInputException(noSuchQuantity);
        }

        existingRecord.Quantity__c = quantity;
        update existingRecord;
        return true;
    }

    @AuraEnabled
    public static Boolean removeFromCart(String userId, String productId) {
        List<Cart__c> existingRecords = [
            SELECT Id FROM Cart__c 
            WHERE UserId__c = :userId AND ProductId__c = :productId AND Status__c = :added
        ];

        if (existingRecords.size() == 0) return false;

        delete existingRecords;
        return true;
    }

    @AuraEnabled
    public static List<Cart__c> getCart(String userId) {
        return getCartUsingStatus(userId, added);
    }

    @AuraEnabled
    public static List<Cart__c> getPaidItems(String userId) {
        return getCartUsingStatus(userId, paid);
    }

    private static List<Cart__c> getCartUsingStatus(String userId, String status) {
        return [
            SELECT 
                Id, UserId__c, Quantity__c,
                ProductId__r.Id, ProductId__r.Name, ProductId__r.InStock__c, 
                ProductId__r.Image__c, ProductId__r.Price__c
            FROM Cart__c
            WHERE UserId__c = :userId
          		AND Status__c = :status
        ];
    }

    @AuraEnabled
    public static Integer getCartItemsCount(String userId) {
        return [
            SELECT COUNT()
            FROM Cart__c
            WHERE UserId__c = :userId
                  AND Status__c = :added
        ];
    }

    @AuraEnabled
    public static Boolean payForOrder(String userId) {
        List<Cart__c> cart = getCart(userId);

        Double bill = 0;
        for (Cart__c item: cart) {
            bill += item.Quantity__c * item.ProductId__r.Price__c;
        }

        if (!OnlineStoreBankingController.widthdrawFromCard(userId, bill)) return false;

        List<Product__c> products = new List<Product__c>();
        for (Cart__c item : cart) {
            if (item.Quantity__c < item.ProductId__r.InStock__c) throw new InvalidInputException(noSuchQuantity);
            item.Status__c = paid;
            products.add(item.ProductId__r);
        }
        update cart;
        update products;
        return true;
    }
}